import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";
import { RefreshCw, Loader2, Wifi, WifiOff } from "lucide-react";
import { api } from "../lib/api";
import { useTheme } from "../context/ThemeContext";
import { useAuth } from "../context/AuthContext";

interface InsightsResponse { metricsSummary: string; narrative: string }
interface AtRisk { customerId: string; churnRisk: number; churnRiskLabel: string; maintenanceDueScore: number; customer: { name: string; phone: string } }
interface ForecastDay { date: string; weekday: number; expectedVisits: number; sampleSize: number }

const WEEKDAY_LABEL = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export function AIInsights() {
  const { user } = useAuth();
  // Recompute is MANAGER's operational action, not ADMIN's oversight-only view of this
  // page (see [[project-kariza-roles-separation]]) -- hide it rather than show a button
  // that 403s.
  const canRecompute = user?.role === "MANAGER";
  const { theme } = useTheme();
  const tickFill = theme === "dark" ? "#9aa7ae" : "#566873";
  const qc = useQueryClient();
  const { data: status } = useQuery({ queryKey: ["ai-status"], queryFn: () => api.get<{ ollamaAvailable: boolean }>("/ai/status") });
  const { data: insights, isLoading, refetch, isFetching } = useQuery({
    queryKey: ["ai-insights"],
    queryFn: () => api.get<InsightsResponse>("/ai/insights"),
    staleTime: Infinity,
  });
  const { data: atRisk } = useQuery({ queryKey: ["ai-at-risk"], queryFn: () => api.get<AtRisk[]>("/ai/insights/at-risk") });
  const { data: forecast } = useQuery({ queryKey: ["ai-forecast"], queryFn: () => api.get<ForecastDay[]>("/ai/forecast?days=7") });

  const recompute = useMutation({
    mutationFn: () => api.post("/ai/insights/recompute"),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["ai-at-risk"] }),
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-end gap-3">
        {status?.ollamaAvailable ? (
          <span className="badge-done"><Wifi size={12} /> Local AI online</span>
        ) : (
          <span className="badge-danger"><WifiOff size={12} /> Local AI offline</span>
        )}
        {canRecompute && (
          <button className="btn-secondary text-xs" onClick={() => recompute.mutate()} disabled={recompute.isPending}>
            <RefreshCw size={14} className={recompute.isPending ? "animate-spin" : ""} /> Recompute scores
          </button>
        )}
      </div>

      <div className="card">
        <h3 className="font-semibold text-ink-200 mb-2">Manager insight (generated by local LLM)</h3>
        {(isLoading || isFetching) && (
          <div className="flex items-center gap-2 text-ink-500 text-sm py-4">
            <Loader2 className="animate-spin" size={16} /> Generating narrative on local CPU -- this can take up to a minute...
          </div>
        )}
        {insights && !isFetching && (
          <>
            <pre className="text-xs text-ink-500 whitespace-pre-wrap bg-ink-950 rounded-sm p-3 mb-3">{insights.metricsSummary}</pre>
            <p className="text-sm text-ink-200 whitespace-pre-wrap">{insights.narrative}</p>
          </>
        )}
        <button className="btn-secondary text-xs mt-3" onClick={() => refetch()}>Regenerate narrative</button>
      </div>

      <div className="card">
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-semibold text-ink-200">Expected demand &middot; next 7 days</h3>
          {forecast?.some((d) => d.sampleSize < 3) && (
            <span className="panel-title">Limited history on some days</span>
          )}
        </div>
        <ResponsiveContainer width="100%" height={200}>
          <BarChart data={forecast}>
            <XAxis dataKey="weekday" tickFormatter={(w) => WEEKDAY_LABEL[w]} tick={{ fontSize: 11, fill: tickFill }} />
            <YAxis tick={{ fontSize: 11, fill: tickFill }} allowDecimals={false} />
            <Tooltip
              formatter={(value: number, _name, item) => [`${value} vehicles`, item.payload.date]}
              contentStyle={{ background: "#161c1f", border: "1px solid #252e33", borderRadius: 2 }}
              labelFormatter={() => ""}
            />
            <Bar dataKey="expectedVisits" fill="#1ea696" radius={2} />
          </BarChart>
        </ResponsiveContainer>
      </div>

      <div className="card">
        <h3 className="font-semibold text-ink-200 mb-3">Customers flagged by the AI (churn-risk &amp; maintenance-due model)</h3>
        <table className="w-full text-sm">
          <thead className="text-ink-500 text-left"><tr><th className="py-2">Customer</th><th className="py-2">Churn risk</th><th className="py-2">Maintenance due</th></tr></thead>
          <tbody className="divide-y divide-ink-800">
            {atRisk?.map((c) => (
              <tr key={c.customerId}>
                <td className="py-2">{c.customer.name}<div className="text-xs text-ink-400">{c.customer.phone}</div></td>
                <td className="py-2">
                  <span className={c.churnRiskLabel === "HIGH" ? "badge-danger" : "badge-warn"}>
                    {c.churnRiskLabel} ({Math.round(c.churnRisk * 100)}%)
                  </span>
                </td>
                <td className="py-2">{Math.round(c.maintenanceDueScore * 100)}%</td>
              </tr>
            ))}
            {!atRisk?.length && <tr><td colSpan={3} className="py-4 text-ink-400">No medium/high risk customers right now.</td></tr>}
          </tbody>
        </table>
      </div>
    </div>
  );
}
